#ifndef DZE_STORAGE_MANAGEMENT_DEFINES
#define DZE_STORAGE_MANAGEMENT_DEFINES

// Shared by the dialog config and its SQF callbacks.
#define DZE_STORAGE_IDD 711196
#define DZE_STORAGE_IDC_BACKGROUND 7200
#define DZE_STORAGE_IDC_TITLE 7201
#define DZE_STORAGE_IDC_DESCRIPTION 7202
#define DZE_STORAGE_IDC_PLAYERS_LABEL 7203
#define DZE_STORAGE_IDC_FRIENDS_LABEL 7204
#define DZE_STORAGE_IDC_PLAYERS 7205
#define DZE_STORAGE_IDC_FRIENDS 7206
#define DZE_STORAGE_IDC_ADD 7207
#define DZE_STORAGE_IDC_REMOVE 7208
#define DZE_STORAGE_IDC_CLOSE 7209

#define DZE_STORAGE_CT_TEXT 0
#define DZE_STORAGE_CT_LISTBOX 5
#define DZE_STORAGE_CT_SHORTCUT_BUTTON 16
#define DZE_STORAGE_ST_LEFT 0
#define DZE_STORAGE_ST_LIST 16
#define DZE_STORAGE_ST_BUTTON 194

#define DZE_STORAGE_FONT "Zeppelin32"
#define DZE_STORAGE_FONT_SIZE "(((((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)"
#define DZE_STORAGE_LIST_FONT_SIZE 0.035
#define DZE_STORAGE_DESCRIPTION_FONT_SIZE 0.025
#define DZE_STORAGE_COLOR_TEXT 1,1,1,1
#define DZE_STORAGE_COLOR_DISABLED 1,1,1,0.25
#define DZE_STORAGE_COLOR_BACKGROUND 0,0,0,0.8
#define DZE_STORAGE_COLOR_ACCENT 0.3843,0.7019,0.8862,0.5
#define DZE_STORAGE_COLOR_HOVER 0.9,0.9,0.9,0.5
#define DZE_STORAGE_COLOR_LIST 0.1,0.1,0.1,0.8
#define DZE_STORAGE_COLOR_SELECTION 0.7,0.7,0.7,0.5
#define DZE_STORAGE_BUTTON_TEXTURE "#(argb,8,8,3)color(1,1,1,1)"

#define DZE_STORAGE_X 0.30
#define DZE_STORAGE_Y 0.15
#define DZE_STORAGE_W 0.30
#define DZE_STORAGE_H 0.65
#define DZE_STORAGE_TITLE_H 0.05
#define DZE_STORAGE_LEFT_X 0.31
#define DZE_STORAGE_RIGHT_X 0.45
#define DZE_STORAGE_COLUMN_W 0.13
#define DZE_STORAGE_DESCRIPTION_Y 0.30
#define DZE_STORAGE_DESCRIPTION_W 0.28
#define DZE_STORAGE_DESCRIPTION_H 0.05
#define DZE_STORAGE_LABEL_Y 0.38
#define DZE_STORAGE_LABEL_H 0.03
#define DZE_STORAGE_LIST_Y 0.41
#define DZE_STORAGE_LIST_H 0.30
#define DZE_STORAGE_ADD_X 0.33
#define DZE_STORAGE_REMOVE_X 0.47
#define DZE_STORAGE_BUTTON_Y 0.72
#define DZE_STORAGE_BUTTON_W 0.08
#define DZE_STORAGE_BUTTON_H 0.039216
#define DZE_STORAGE_CLOSE_X 0.40
#define DZE_STORAGE_CLOSE_Y 0.75

#endif
